### PR TITLE
first run scripts

### PR DESCRIPTION
**Pull request by kaechb**

### CODE REVIEW

**Comment by kaechb** [comment]
run.sh for the training,
firstrun.sh for validation

**Comment by michelif** [comment]
hi, what is this pull request? moreover why it continues updating?

**Comment by kaechb** [comment]
Yes that was me.
It keeps updating because I showed it to Mauro, he had the opinion that I can just push if i switch to a new branch.
Is there any problem with that?


________________________________
Von: michelif <notifications@github.com>
Gesendet: Dienstag, März 5, 2019 2:13 PM
An: michelif/HHbbgg_ETH
Cc: Kaechb; State change
Betreff: Re: [michelif/HHbbgg_ETH] first run scripts (#8)


hi, what is this pull request? moreover why it continues updating?

**Comment by kaechb** [comment]
Oh sorry i read that wrong. Its just for me to have a own branch, where i can push my stuff to.


________________________________
Von: Benno Kaech <benno.kaech@hotmail.com>
Gesendet: Dienstag, März 5, 2019 2:25 PM
An: michelif/HHbbgg_ETH; michelif/HHbbgg_ETH
Cc: State change
Betreff: Re: [michelif/HHbbgg_ETH] first run scripts (#8)

Yes that was me.
It keeps updating because I showed it to Mauro, he had the opinion that I can just push if i switch to a new branch.
Is there any problem with that?


________________________________
Von: michelif <notifications@github.com>
Gesendet: Dienstag, März 5, 2019 2:13 PM
An: michelif/HHbbgg_ETH
Cc: Kaechb; State change
Betreff: Re: [michelif/HHbbgg_ETH] first run scripts (#8)


hi, what is this pull request? moreover why it continues updating?

**Comment by michelif** [comment]
yes, you can push to your own branch without creating a pull request to my branch.
i'll close this pull request

**Pull request closed without merging**
